version: '3.5'
services:
  storage_manager:
    container_name: storage_manager
    image: python:3.8
    volumes:
      - ./storage_manager:/storage_manager
      - ./common:/storage_manager/common
    entrypoint: python3 /storage_manager/main.py
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - PYTHONUNBUFFERED=1
      - STORAGE_MANAGER_WRITE_PORT=12345
      - STORAGE_MANAGER_READ_PORT=12346
      - READ_PROCESS_AMOUNT=64
      - STORAGE_MANAGER_MINED_PER_MINUTE_PORT=12347
      - MINED_PER_MINUTE_PROCESS_AMOUNT=64
    networks:
      - blockchain_net

  blockchain_server:
    container_name: blockchain_server
    image: python:3.8
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - PYTHONUNBUFFERED=1
      - MINERS_AMOUNT=4
      - BLOCK_BUILDER_PORT=12345
      - MAX_BLOCKS_ENQUEUED=2048
      - MINED_COUNTER_PORT=12346
      - STORAGE_MANAGER_HOST=storage_manager
      - STORAGE_MANAGER_WRITE_PORT=12345
    volumes:
      - ./blockchain:/blockchain
      - ./common:/blockchain/common
    entrypoint: python3 /blockchain/main.py
    networks:
      - blockchain_net
    depends_on:
      - storage_manager

networks:
  blockchain_net:
    name: blockchain_net
    ipam:
      driver: default
      config:
        - subnet: 173.25.125.0/24