MINER_ID_LEN_IN_BYTES = 4
ALL_MINERS = 0
MINED_PER_MINER_SIZE_LEN_IN_BYTES = 4
ADD_SUCCESSFUL_MINING_OP = 1
ADD_WRONG_MINING_OP = 2
SUCCESSFUL_INDEX = 0
WRONG_INDEX = 1

MAX_ENTRY_SIZE_IN_BYTES = 65356
CHUNK_SIZE_LEN_IN_BYTES = 4

DATE_SIZE_LEN_IN_BYTES = 4
DATE_STRING_FORMAT = '%d/%m/%Y %H:%M'
HASH_LIST_SIZE_LEN_IN_BYTES = 4